name: "Multi Pipeline"

#Trigger action when a push is done to master / production branch
on:
  push:
    branches:
      - master
      - production
  pull_request:
    branches:
      - master

jobs:
  on-push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: "Print Hello World"
        run: echo "Hello World"

  on-pull-reqest:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: "Print pull request"
        run: echo "on-pullrequest"
