name: "Hello World"

#Trigger action when a push is done to master / production branch
on:
  push:
    branches:
      - master
      - production
  pull_request:
    branches:
      - master

jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: "Print Hello World"
        run: echo "Hello World"

  on-pull-reqest:
    runs-on: ubuntu-latest
    steps:
      - name: "Print pull request"
        run: echo "on-pullrequest"
